apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      imagePullSecrets:
        - name: {{ .Values.apache2.imagePullSecret | quote }}
      containers:
        - name: apache
          image: {{ .Values.apache2.image | quote }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-service
spec:
  selector:
    app: apache2
  ports:
    - port: 80
      targetPort: 80
