apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: boardmaria-route
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentGateway.name | quote }}
      namespace: {{ .Values.gateway.parentGateway.namespace | quote }}
      sectionName: {{ .Values.gateway.parentGateway.sectionName | quote }}
  hostnames:
    - {{ .Values.gateway.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.pathPrefix | quote }}
      backendRefs:
        - name: apache2-service
          port: 80
