{{- $redir := (.Values.gateway.redirect | default dict) -}}
{{- $redirStatus := (get $redir "statusCode" | default 301) -}}
{{- $redirPort := (get $redir "port" | default 443) -}}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-redirect" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentGateway.name | quote }}
      namespace: {{ .Values.gateway.parentGateway.namespace | quote }}
      sectionName: "web"
  hostnames:
    - {{ .Values.gateway.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.pathPrefix | quote }}
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: {{ $redirStatus }}
            port: {{ $redirPort }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-websecure" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentGateway.name | quote }}
      namespace: {{ .Values.gateway.parentGateway.namespace | quote }}
      sectionName: {{ .Values.gateway.parentGateway.sectionName | quote }}
  hostnames:
    - {{ .Values.gateway.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.gateway.pathPrefix | quote }}
      backendRefs:
        - name: apache2-service
          port: 80
