apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      {{- if and .Values.mariadb.persistence .Values.mariadb.persistence.enabled }}
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: {{ .Values.mariadb.persistence.claimName }}
      {{- end }}
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          {{- if and .Values.mariadb.persistence .Values.mariadb.persistence.enabled }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
---
{{- if and .Values.mariadb.persistence .Values.mariadb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mariadb.persistence.claimName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: mariadb
spec:
  {{- if .Values.mariadb.persistence.storageClassName }}
  storageClassName: {{ .Values.mariadb.persistence.storageClassName | quote }}
  {{- end }}
  accessModes:
  {{- range .Values.mariadb.persistence.accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size | quote }}
{{- end }}
